### ISSUE TITLE
Verbindung Multispektralkamera und IPC

### ISSUE THREAD

**Issue by DomenikINBW** [vitrum-connect/5gla-camera-integration-script#19]
Anschließen der Multispektralkamera an den IPC/die VM

Diese User Story gilt als erfüllt, wenn...

... die Kamera von der VM aus angepingt werden kann. 
... das camera-integration script fehlerfrei ausgeführt werden kann (Verbindung noch nicht über der 5G Netz)

**Comment by Chromeggs** [comment]
Moin @DomenikINBW , 
Auch das von idr gestzte Auslieferungsdatum für diese USerstory liegt bereits seit einer Woche in der Vergangenheit.
Es ist zwar nicht höchste Priorität, aber entspricht dennoch nicht der Philosophie von Kanban-Sprints, dass die Sachen einfach liegen bleiben (wenn das denn so ist - kann ja auch sein, dass du hier einfach noch nicht alle Infos aktualisiert hast).
Lass mal hören
VG Ben

**Comment by DomenikINBW** [comment]
Moin @Chromeggs ,
Das Lieferdatum konnte ich nicht halten, da ich letzte Woche noch den Robotikkurs betreut habe. Ich habe dies aber heute abgeschlossen. Der Code gibt keine Fehlermeldungen mehr.

Grüße
Domenik
