### ISSUE TITLE
MECSware Bugreport

### ISSUE THREAD

**Issue by DomenikINBW** [vitrum-connect/5gla-camera-integration-script#28]
Beschreibung/Zusammenfassung des Mail-Verkehrs mit MECSware zu Problemen mit dem MECS-UE (IPC) und dem 5G Netz.

Problem1: UE verbindet sich nicht mit dem 5G-Netz wenn längere Zeit keine Verbindung bestand. 
--> Antwort MECSware: Durch die SUCI Funktion im 5G-Netz versuchen sich Endgeräte von öffentlichen 5G-Netzen auf das Campusnetzwerk zu verbinden. Das Problem wird mit der Version MECS 3.15.1 gelöst. Außerdem sollen wir das Update auf UE 1.4 durchführen.

Problem2: auf der Managementoberfläche des UE werden nach Update auf UE 1.4 die VMs nicht mehr angezeigt obwohl diese weiterhin existieren und laufen. auch eine Neuangelegte VM wird nach Refresh der Seite nicht mehr angezeigt.
--> MECSware ist informiert, zuständiger Mitarbeiter ist in KW 32 aus dem Urlaub zurück und untersucht das Problem.

**Comment by DomenikINBW** [comment]
@Vitrum-LL @saschadoemer zu Problem1 sagte Herr Musiol, das wir uns wenn das Problem nochmal auftritt uns zeitnah melden sollen, damit sich MECSware die Logs ansehen kann. Könnt ihr mit daran denken die Zeit zu dokumentieren, wenn wir versuchen uns zu verbinden.

**Comment by Chromeggs** [comment]
Moin @DomenikINBW : gibt es hierzu etwas neues? Ist ja schon wieder zwei Wochen alt.
Zu diesem Topic fehlt im übrigen ein voraussichtliches Auslieferungsdatum. Kannst du das noch setzen?
Cheers
Ben

**Comment by DomenikINBW** [comment]
Updates durchgeführt. Antennen kommen stand Donnerstag nicht online. Spreche mit dem MECsware support und bin dran bis zum Hackathon

**Comment by DomenikINBW** [comment]
Antennen online 5G Netzwerk auf neuestem Stand, IPC update muss noch durchgeführt werden. Dadurch löst sich wahrscheinlich auch das letzte Problem

**Comment by Chromeggs** [comment]
Hi @DomenikINBW : kannst du das Datum zur Auslieferung dieser Ueerstory noch realistisch anpassen (sollte in der Zukunft liegen)

**Comment by DomenikINBW** [comment]
Beim Hackathon sind noch Probleme mit der Verbindung aufgetreten. Am 21.08.2024 11:30 Treffen zwischen Alexei, Sascha, Christopher und mir mit MECSware. 
Herr Reidelstütz tippt auf ein MTU-Problem. Das tritt anscheinend aktuell bei denen auf. Es wird an einem Fix gearbeitet der aber noch dauert, eventuell gibt es einen Workaround

**Comment by DomenikINBW** [comment]
Alle Bugs vorerst behoben. Wir warten noch auf den Offiziellen Bug Fix als Release. Anschließend machen wir keine Updates mehr um unseren Versuch nicht zu gefärden.
